"""added is_authenticated

Revision ID: 01f50d198e93
Revises: 0800887dc68b
Create Date: 2020-03-11 17:11:41.046647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f50d198e93'
down_revision = '0800887dc68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_authenticated')
    # ### end Alembic commands ###
