"""extras11

Revision ID: 04843be06f47
Revises: 4eacdbe3770a
Create Date: 2020-03-23 00:02:03.020727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04843be06f47'
down_revision = '4eacdbe3770a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pizza_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'pizzas', ['pizza_id'], ['id'])
    op.drop_constraint('toppings_association_pizza_id_fkey', 'toppings_association', type_='foreignkey')
    op.drop_column('toppings_association', 'pizza_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toppings_association', sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('toppings_association_pizza_id_fkey', 'toppings_association', 'pizzas', ['pizza_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'pizza_id')
    # ### end Alembic commands ###
