"""added the topping model

Revision ID: 22fc8eb3b031
Revises: 695a87f9c5ec
Create Date: 2020-03-17 11:20:05.420944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fc8eb3b031'
down_revision = '695a87f9c5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Topping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topping_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Topping')
    # ### end Alembic commands ###
