"""added pizza and nonpizza tables

Revision ID: 2f3d9e41e157
Revises: 4aedbe35fdd7
Create Date: 2020-03-14 17:32:09.442841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3d9e41e157'
down_revision = '4aedbe35fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizzatype', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=128), nullable=False),
    sa.Column('toppings', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPtype', sa.String(length=128), nullable=False),
    sa.Column('extras', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sub')
    op.drop_table('Pizza')
    # ### end Alembic commands ###
