"""linking2

Revision ID: 3c50b3d26f5a
Revises: a18fd2f776ed
Create Date: 2020-03-18 17:22:51.403026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c50b3d26f5a'
down_revision = 'a18fd2f776ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order-items', sa.Column('item_nonpizza_id', sa.Integer(), nullable=True))
    op.add_column('order-items', sa.Column('item_pizza_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order-items', 'non-pizzas', ['item_nonpizza_id'], ['id'])
    op.create_foreign_key(None, 'order-items', 'pizzas', ['item_pizza_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order-items', type_='foreignkey')
    op.drop_constraint(None, 'order-items', type_='foreignkey')
    op.drop_column('order-items', 'item_pizza_id')
    op.drop_column('order-items', 'item_nonpizza_id')
    # ### end Alembic commands ###
