"""cost added to Extra

Revision ID: 403f329c4f15
Revises: de567f6e79d5
Create Date: 2020-03-17 16:04:39.657164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403f329c4f15'
down_revision = 'de567f6e79d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Extra', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Extra', 'cost')
    # ### end Alembic commands ###
