"""changed authenticated

Revision ID: 4aedbe35fdd7
Revises: a24b8a0db1fe
Create Date: 2020-03-14 15:40:36.572865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aedbe35fdd7'
down_revision = 'a24b8a0db1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_is_active')
    op.drop_column('users', '_is_authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('_is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
