"""extras6

Revision ID: 4eacdbe3770a
Revises: 9f27770fa0c5
Create Date: 2020-03-22 23:00:13.148232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eacdbe3770a'
down_revision = '9f27770fa0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_pizza_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'pizza_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_pizza_id_fkey', 'products', 'pizzas', ['pizza_id'], ['id'])
    # ### end Alembic commands ###
