"""added pizza and nonpizza tables.

Revision ID: 691a32cdb0ec
Revises: 2f3d9e41e157
Create Date: 2020-03-14 17:32:44.035508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '691a32cdb0ec'
down_revision = '2f3d9e41e157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Non-Pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPtype', sa.String(length=128), nullable=False),
    sa.Column('extras', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sub',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sub_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('NPtype', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('extras', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Sub_pkey')
    )
    op.drop_table('Non-Pizza')
    # ### end Alembic commands ###
