"""made is_authenticated a property

Revision ID: 6940030adbe5
Revises: 01f50d198e93
Create Date: 2020-03-14 15:06:10.583375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6940030adbe5'
down_revision = '01f50d198e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
