"""added boolean for admin permissions

Revision ID: 695a87f9c5ec
Revises: 691a32cdb0ec
Create Date: 2020-03-15 20:51:43.796417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a87f9c5ec'
down_revision = '691a32cdb0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
