"""removed product type id

Revision ID: 6a3458cecbd7
Revises: 8dc230c5fc7c
Create Date: 2020-03-21 22:06:22.894106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3458cecbd7'
down_revision = '8dc230c5fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non-pizzas', 'product_type_id')
    op.drop_column('pizzas', 'product_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('non-pizzas', sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
