"""orderitem update


Revision ID: 6a71a31de2e5
Revises: ed74e8c77a98
Create Date: 2020-03-21 16:09:28.581951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71a31de2e5'
down_revision = 'ed74e8c77a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order-items', 'item_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order-items', sa.Column('item_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
