"""orderitem added

Revision ID: 76e93cb94501
Revises: f9ee38f23557
Create Date: 2020-03-18 14:55:17.691724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76e93cb94501'
down_revision = 'f9ee38f23557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non-pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('pizzatype', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=128), nullable=False),
    sa.Column('toppings', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topping_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extra', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('nonpizza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nonpizza_id'], ['non-pizzas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order-items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Topping')
    op.drop_table('Order-Item')
    op.drop_table('Extra')
    op.drop_table('Pizza')
    op.drop_table('Non-Pizza')
    op.drop_table('Order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Order_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Order_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Order_pkey')
    )
    op.create_table('Non-Pizza',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Non-Pizza_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Non-Pizza_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Pizza',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Pizza_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('pizzatype', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('toppings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Pizza_pkey')
    )
    op.create_table('Extra',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Extra_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('extra', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('nonpizza_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nonpizza_id'], ['Non-Pizza.id'], name='Extra_nonpizza_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Extra_pkey')
    )
    op.create_table('Order-Item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Order-Item_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Order-Item_pkey')
    )
    op.create_table('Topping',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Topping_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('topping_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Topping_pkey')
    )
    op.drop_table('order-items')
    op.drop_table('orders')
    op.drop_table('extras')
    op.drop_table('toppings')
    op.drop_table('pizzas')
    op.drop_table('non-pizzas')
    # ### end Alembic commands ###
