"""boulean

Revision ID: 8407b2816cf4
Revises: 76e93cb94501
Create Date: 2020-03-18 16:07:34.112461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8407b2816cf4'
down_revision = '76e93cb94501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('checkedout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'checkedout')
    # ### end Alembic commands ###
