"""linked the toppings and pizza tables

Revision ID: 8dc230c5fc7c
Revises: 6a71a31de2e5
Create Date: 2020-03-21 22:04:41.702260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc230c5fc7c'
down_revision = '6a71a31de2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toppings_association',
    sa.Column('topping_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], ),
    sa.PrimaryKeyConstraint('topping_id', 'pizza_id')
    )
    op.drop_constraint('extras_nonpizza_id_fkey', 'extras', type_='foreignkey')
    op.drop_column('extras', 'nonpizza_id')
    op.add_column('non-pizzas', sa.Column('extra_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'non-pizzas', 'extras', ['extra_id'], ['id'])
    op.add_column('pizzas', sa.Column('no_toppings', sa.Integer(), nullable=True))
    op.drop_column('pizzas', 'toppings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('toppings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pizzas', 'no_toppings')
    op.drop_constraint(None, 'non-pizzas', type_='foreignkey')
    op.drop_column('non-pizzas', 'extra_id')
    op.add_column('extras', sa.Column('nonpizza_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('extras_nonpizza_id_fkey', 'extras', 'non-pizzas', ['nonpizza_id'], ['id'])
    op.drop_table('toppings_association')
    # ### end Alembic commands ###
