"""extras3

Revision ID: 9f27770fa0c5
Revises: a73184dc9996
Create Date: 2020-03-22 22:35:35.935830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f27770fa0c5'
down_revision = 'a73184dc9996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non-pizzas', 'extra_cheese')
    op.add_column('products', sa.Column('extra_cheese', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'extra_cheese')
    op.add_column('non-pizzas', sa.Column('extra_cheese', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
