"""OrderItem added item_type

Revision ID: a18fd2f776ed
Revises: 8407b2816cf4
Create Date: 2020-03-18 17:08:48.039549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18fd2f776ed'
down_revision = '8407b2816cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order-items', sa.Column('item_type', sa.String(length=128), nullable=True))
    op.drop_column('order-items', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order-items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order-items', 'item_type')
    # ### end Alembic commands ###
