"""changed is_* to local

Revision ID: a24b8a0db1fe
Revises: 6940030adbe5
Create Date: 2020-03-14 15:22:02.676987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24b8a0db1fe'
down_revision = '6940030adbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('_is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_is_authenticated')
    op.drop_column('users', '_is_active')
    # ### end Alembic commands ###
