"""extras1

Revision ID: c1edf2b16969
Revises: 6a3458cecbd7
Create Date: 2020-03-22 22:30:57.402597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1edf2b16969'
down_revision = '6a3458cecbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('non-pizzas_extra_id_fkey', 'non-pizzas', type_='foreignkey')
    op.drop_column('non-pizzas', 'extra_id')
    op.add_column('toppings_association', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'toppings_association', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toppings_association', type_='foreignkey')
    op.drop_column('toppings_association', 'product_id')
    op.add_column('non-pizzas', sa.Column('extra_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('non-pizzas_extra_id_fkey', 'non-pizzas', 'extras', ['extra_id'], ['id'])
    # ### end Alembic commands ###
