"""c

Revision ID: de567f6e79d5
Revises: 3f472df8494a
Create Date: 2020-03-17 15:52:02.357937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de567f6e79d5'
down_revision = '3f472df8494a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Non-Pizza', 'type_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Non-Pizza', 'NPtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Non-Pizza', sa.Column('NPtype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('Non-Pizza', 'type_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
