"""foreign keys

Revision ID: ebc4afefde10
Revises: 22fc8eb3b031
Create Date: 2020-03-17 11:58:59.100734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebc4afefde10'
down_revision = '22fc8eb3b031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extra', sa.String(length=128), nullable=True),
    sa.Column('nonpizza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nonpizza_id'], ['Non-Pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Non-Pizza', 'extras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Non-Pizza', sa.Column('extras', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('Extra')
    # ### end Alembic commands ###
